1234

diff --git a/CRMproject/Dockerfile b/CRMproject/Dockerfile
--- a/CRMproject/Dockerfile
+++ b/CRMproject/Dockerfile
@@ -35,6 +35,21 @@ ENV DJANGO_SETTINGS_MODULE CRMproject.settings
 # Copy the .env file
 COPY .env /app/
 
+# Determine the encryption key from the build argument
+ARG encryption_key
+
+# Check if the encryption key is provided
+RUN if [ -z "$encryption_key" ]; then \
+      echo "Error: Encryption key not provided."; \
+      exit 1; \
+    fi
+
+# Encrypt the .env file using the encryption key
+RUN openssl aes-256-cbc -e -in .env -out .env.encrypted -k $encryption_key
+
+# Remove the original .env file
+RUN rm .env
+
 # Upgrade pip to the latest version
 RUN pip install --trusted-host pypi.python.org --upgrade pip -v
 
